AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: Engineering Delivery Hub backend

Globals:
  Function:
    Runtime: nodejs24.x
    Architectures:
      - arm64
    Timeout: 10
    MemorySize: 256
    Environment:
      Variables:
        PROJECTS_TABLE_NAME: engineering-delivery-projects

Resources:
  GetProjectsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/handlers/getProjects.handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Scan
              Resource: arn:aws:dynamodb:us-east-2:867719008416:table/engineering-delivery-projects
      Events:
        GetProjects:
          Type: HttpApi
          Properties:
            Path: /projects
            Method: GET

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - src/handlers/getProjects.ts
        Minify: false
        Target: es2022
        Sourcemap: true

  CreateProjectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/handlers/createProject.handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: arn:aws:dynamodb:us-east-2:867719008416:table/engineering-delivery-projects
      Events:
        CreateProject:
          Type: HttpApi
          Properties:
            Path: /projects
            Method: POST

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - src/handlers/createProject.ts
        Minify: false
        Target: es2022
        Sourcemap: true

Outputs:
  GetProjectsApiUrl:
    Description: URL for the projects API
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/projects"
